[package]
name = "qsolve"
version = "1.0.1"
authors = ["Dan Schafer <dan.schafer@gmail.com>"]
edition = "2024"
description = "A library and command-line tool for solving Queens puzzles"
documentation = "https://docs.rs/qsolve"
readme = "README.md"
repository = "https://github.com/dschafer/qsolve"
license = "MIT OR Apache-2.0"
keywords = ["Queens", "puzzle", "solver"]
categories = ["command-line-utilities"]
exclude = [
    "benches/*",
    "media/*",
    "games/*",
    "tests/*",
]

[badges]
maintenance.status = "as-is"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"], optional = true }
crossterm = { version = "0.29.0", optional = true }
ctrlc = { version = "3.4.6", optional = true }
env_logger = { version = "0.11.6", optional = true }
image = { version = "0.25.6", optional = true }
itertools = "0.14.0"
log = "0.4.25"
owo-colors = "4.1.0"

[dev-dependencies]
assert_cmd = "2.0.17"
criterion = { version = "0.5", features = ["html_reports"] }
predicates = "3.1.3"
regex = "1.11.1"

[features]
default = ["cli", "image"]
cli = [
    "dep:clap",
    "dep:crossterm",
    "dep:ctrlc",
    "dep:env_logger",
]
image = ["dep:image"]

[profile.release]
debug = true

[lib]
name = "qsolve"
path = "src/lib.rs"

[[bin]]
name = "qsolve"
path = "src/main.rs"
required-features = ["cli"]

[[test]]
name = "command_line_runs"
required-features = ["cli"]

[[test]]
name = "reads_all_images"
required-features = ["image"]

[[bench]]
name = "qsolvebench"
harness = false
